language: node_js
node_js:
  - "8.1.3"
install:
  - npm install
before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
script:
  - npm run prod:build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - npm run lh -- https://lithub-38a37.firebaseapp.com/
